version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/enumpowerset/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/nullable/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/whitespaces/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/naming/"
    schedule:
      interval: "daily"
