version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/whichlicense/testing-libs
    token: ${{ github.token }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/enumpowerset/"
    schedule:
      interval: "daily"
