version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/whichlicense
    username: ${{ secrets.GH_ACCT }}
    password: ${{ secrets.GH_PKG }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "grevend"
  - package-ecosystem: "gradle"
    directory: "/enumpowerset/"
    schedule:
      interval: "daily"
    registries:
      - github-packages
    reviewers:
      - "grevend"
  - package-ecosystem: "gradle"
    directory: "/nullable/"
    schedule:
      interval: "daily"
    registries:
      - github-packages
    reviewers:
      - "grevend"
  - package-ecosystem: "gradle"
    directory: "/whitespaces/"
    schedule:
      interval: "daily"
    registries:
      - github-packages
    reviewers:
      - "grevend"
  - package-ecosystem: "gradle"
    directory: "/naming/"
    schedule:
      interval: "daily"
    reviewers:
      - "grevend"
